version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./target/legacy-plugin.jar:/opt/keycloak/providers/legacy-plugin.jar
    command: [ "start-dev", "--log-level=DEBUG" ]
    networks:
      - mynetwork

  app:
    image: three
    ports:
      - "3000:3000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
